CAMERA_INDEX = 0
YOLO_MODEL = "yolov8n.pt"

ENABLE_AUDIO_DETECTION = False
ENABLE_IMAGE_DETECTION = True

RECORD_SECONDS = 3
SAMPLE_RATE = 48000
AUDIO_INTERVAL = 5

LAT = 57.048
LON = 9.918

SPECIES_CONFIDENCE = 0.6
BOX_CONFIDENCE = 0.25

MIN_BIRD_SIZE = 80
SAVE_COOLDOWN = 15

SNAPSHOT_DIR = "snapshots"
LOG_FILE = "sightings.csv"